name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  call-publish:
    uses: qntx/workflows/.github/workflows/publish-pypi.yml@v2.0.0
    permissions:
      contents: read
      id-token: write
      attestations: write
    with:
      python-version: '3.13'
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN || secrets.PYPI_API_TOKEN }}
